import base64
import tempfile

import pytest


# This base64-encoded byte array is a content of following sample Parquet file:
#
# A | B
# --+--
# 1 | 4
# 2 | 5
# 3 | 6
#
sample_table_b64 = (
    "UEFSMRUEFTAVLkwVBhUEEgAAGAQBAAkBPAIAAAAAAAAAAwAAAAAAAAAVABUUFRgsFQYVBBUGF"
    "QYcGAgDAAAAAAAAABgIAQAAAAAAAAAWACgIAwAAAAAAAAAYCAEAAAAAAAAAAAAACiQCAAAABg"
    "ECAyQAJuQBHBUEGTUEAAYZGAFBFQIWBhbaARbcASZSJggcGAgDAAAAAAAAABgIAQAAAAAAAAA"
    "WACgIAwAAAAAAAAAYCAEAAAAAAAAAABksFQQVBBUCABUAFQQVAgAAABUEFTAVLkwVBhUEEgAA"
    "GAQEAAkBPAUAAAAAAAAABgAAAAAAAAAVABUUFRgsFQYVBBUGFQYcGAgGAAAAAAAAABgIBAAAA"
    "AAAAAAWACgIBgAAAAAAAAAYCAQAAAAAAAAAAAAACiQCAAAABgECAyQAJvYEHBUEGTUEAAYZGA"
    "FCFQIWBhbaARbcASbkAyaaAxwYCAYAAAAAAAAAGAgEAAAAAAAAABYAKAgGAAAAAAAAABgIBAA"
    "AAAAAAAAAGSwVBBUEFQIAFQAVBBUCAAAAFQIZPDUAGAZzY2hlbWEVBAAVBCUCGAFBABUEJQIY"
    "AUIAFgYZHBksJuQBHBUEGTUEAAYZGAFBFQIWBhbaARbcASZSJggcGAgDAAAAAAAAABgIAQAAA"
    "AAAAAAWACgIAwAAAAAAAAAYCAEAAAAAAAAAABksFQQVBBUCABUAFQQVAgAAACb2BBwVBBk1BA"
    "AGGRgBQhUCFgYW2gEW3AEm5AMmmgMcGAgGAAAAAAAAABgIBAAAAAAAAAAWACgIBgAAAAAAAAA"
    "YCAQAAAAAAAAAABksFQQVBBUCABUAFQQVAgAAABa4AxYGJuQBFrgDFAAAGRwYDEFSUk9XOnNj"
    "aGVtYRjsAS8vLy8vNmdBQUFBUUFBQUFBQUFLQUF3QUJnQUZBQWdBQ2dBQUFBQUJBd0FNQUFBQ"
    "UNBQUlBQUFBQkFBSUFBQUFCQUFBQUFJQUFBQkVBQUFBQkFBQUFOVC8vLzhBQUFFQ0hBQUFBQX"
    "dBQUFBRUFBQUFBQUFBQU1ULy8vOEFBQUFCUUFBQUFBRUFBQUJDQUFBQUVBQVVBQWdBQmdBSEF"
    "Bd0FBQUFRQUJBQUFBQUFBQUVDSkFBQUFCUUFBQUFFQUFBQUFBQUFBQWdBREFBSUFBY0FDQUFB"
    "QUFBQUFBRkFBQUFBQVFBQUFFRUFBQUE9ABgicGFycXVldC1jcHAgdmVyc2lvbiAxLjUuMS1TT"
    "kFQU0hPVBksHAAAHAAAABoCAABQQVIx"
)


@pytest.fixture
def sample_file():
    with tempfile.NamedTemporaryFile() as f:
        f.write(base64.b64decode(sample_table_b64))
        f.flush()
        yield f.name
